export const FILTER_USER_LIST = 'FILTER_USER_LIST'
export const SET_DEFAULT_VALUES = 'SET_DEFAULT_VALUES'
export const SET_NAME = 'SET_NAME'
export const SET_MIN_AGE = 'SET_MIN_AGE'
export const SET_MAX_AGE = 'SET_MAX_AGE'
export const SET_GENDER = 'SET_GENDER'